out/genshi: fix `_simplify_stream`
In `_simplify_stream`, when an expression evaluates to a stream that cannot be fully simplified to a string, the function now returns the updated stream immediately instead of continuing to append to `parts`.

This aligns with the behavior of other non-textual events in the stream.

Fixed by Junie AI, tests failed before this:

ERROR: tests.markup.test_genshi.test_stream_preserved
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tw/w/flatland/tests/markup/test_genshi.py", line 138, in test_stream_preserved
    rendered = render(markup, u'xhtml', schema)
  File "/Users/tw/w/flatland/tests/markup/_util.py", line 153, in render_genshi
    return _render_genshi(markup, language, schema, **context)
  File "/Users/tw/w/flatland/tests/markup/_util.py", line 179, in _render_genshi
    output = template.generate(**kw).render(language)
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/core.py", line 182, in render
    return encode(generator, method=method, encoding=encoding, out=out)
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/output.py", line 58, in encode
    return _encode(''.join(list(iterator)))
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/output.py", line 353, in __call__
    for kind, data, pos in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/output.py", line 673, in __call__
    for kind, data, pos in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/output.py", line 778, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/output.py", line 597, in __call__
    for ev in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/core.py", line 290, in _ensure
    for event in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/template/base.py", line 639, in _include
    for event in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/template/markup.py", line 329, in _match
    for event in stream:
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/template/base.py", line 619, in _flatten
    stream = _apply_directives(data[1], data[0], ctxt, vars)
  File "/Users/tw/w/flatland-env/lib/python3.9/site-packages/genshi/template/base.py", line 273, in _apply_directives
    stream = directives[0](iter(stream), directives[1:], ctxt, **vars)
  File "/Users/tw/w/flatland/flatland/out/genshi.py", line 60, in __call__
    return self.process(stream, local, ctxt, vars)
  File "/Users/tw/w/flatland/flatland/out/genshi.py", line 186, in process
    return _rewrite_stream(stream, directives, ctxt, vars, bind)
  File "/Users/tw/w/flatland/flatland/out/genshi.py", line 271, in _rewrite_stream
    contents = _simplify_stream(stream[1:-1], ctxt, vars)
  File "/Users/tw/w/flatland/flatland/out/genshi.py", line 384, in _simplify_stream
    return u''.join(parts)
TypeError: sequence item 0: expected str instance, list found